export const IMAGES = {
  leftArrow: require("./leftArrow.png"),
  rightArrow: require("./rightArrow.png"),
  rightArrowFade: require("./rightArrowFade.png"),
  clothingCircle: require("./clothingCircle.png"),
  clothing: require("./clothing.png"),
  foodCircle: require("./foodCircle.png"),
  shopping: require("./shopping.png"),
  healthCircle: require("./healthCircle.png"),
  health: require("./health.png"),
  food: require("./food.png"),
  housingCircle: require("./housingCircle.png"),
  housing: require("./housing.png"),
  beautyCircle: require("./beautyCircle.png"),
  beauty: require("./beauty.png"),
  back: require("./back.png"),
  noData: require("./noData.png"),
  edit: require("./edit.png"),
  eye: require("./eye.png"),
  eyeOff: require("./eyeOff.png"),
};
